# MVCC : 여러개 한번에 접근했을때 빨리 처리가 됨. (H2 1.4.198 부터 제거됨)
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopWithBoot
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true  : sysout으로 sql찍음
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #로거를 통해서
